version: "3.0"
  
services:
  eosmonitor:
    image: eosmonitor
    build:
      context: .
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 10m
    container_name: eosmonitor
    expose:
      - 18888
    ports:
      - 18888:18888
    volumes:
      - eosmonitor-data-volume:/eosmonitor/db
      - eosmonitor-data-volume:/eosmonitor/logs
      - ./config/server.js:/eosmonitor/config/server.js
      - ./config/tokens.js:/eosmonitor/config/tokens.js

volumes:
  eosmonitor-data-volume:
    external: true